FROM nginx:latest as production
FROM node:16 as compilation
WORKDIR /app
COPY front/ .
RUN npm install
RUN npm i -g @angular/cli@16.2.10
RUN npm -ng run build --prod
FROM production
WORKDIR /app
RUN rm -rf /usr/share/nginx/html/*
COPY --from=compilation /app/dist/tlcfront/ /usr/share/nginx/html/
EXPOSE 80
