FROM ubuntu:22.04

RUN apt update 
RUN apt install -y openjdk-19-jre
RUN apt install -y maven
COPY api/ /api
WORKDIR /api
RUN mvn compile quarkus:dev && mvn package && ./mvw install
WORKDIR /app
RUN mvn compile quarkus:dev && mvn package && ./mvw install 
CMD ["java", "-Djava.library.path=target/lib", "-jar", "target/tlcdemoApp-1.0.0-SNAPSHOT-runner.jar"]
EXPOSE 8080
